In [1]:
#importing the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
#Reading the csv file
data=pd.read_csv('MergeFileCrop.csv.txt')
name = data['label'].unique()
name = list(name)

In [3]:
data.isnull().any()

Unnamed: 0     False
temperature    False
humidity       False
ph             False
rainfall       False
label          False
dtype: bool

In [4]:
data= data.drop('Unnamed: 0',axis=1)

In [5]:
data = data.sample(frac = 1)  
print(data.head(1))

      temperature   humidity        ph  rainfall   label
1207    12.141907  83.568125  5.647202  69.63122  grapes


In [6]:
#count =0
#for i in data['label']:
#        data['label'][i] == count
#        count = count+1
#print(data['label'])

In [7]:
#print(name)

In [8]:
#print(list(number))

In [9]:
#index1 = {"name":name,
#         "number":number}  

In [10]:
data.head(2)

temperature   humidity        ph   rainfall      label
1207    12.141907  83.568125  5.647202  69.631220     grapes
587     30.888831  52.626968  8.634930  55.519324  mothbeans

In [11]:
import seaborn as sns
sns.heatmap(data.corr())

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["label1"] = le.fit_transform(data["label"])
data.head(12)

temperature   humidity        ph    rainfall      label  label1
1207    12.141907  83.568125  5.647202   69.631220     grapes       7
587     30.888831  52.626968  8.634930   55.519324  mothbeans      13
893     27.996279  68.642859  7.327110   46.105852     lentil      10
1127    29.980805  49.486133  6.442393   91.822716      mango      12
1508    21.911913  91.687481  6.499227  117.076128      apple       0
1905    24.694571  81.735888  6.628723   78.584944     cotton       6
1132    35.787774  51.941903  5.395276  100.216061      mango      12
2183    24.592457  56.468296  7.288212  137.704405     coffee       5
278     19.462104  18.728320  7.217018   68.814051   chickpea       3
701     26.734340  68.139997  7.040056   67.150964  blackgram       2
1991    22.008171  81.838961  7.762648   92.236452     cotton       6
1035    27.572781  82.063888  6.435786   91.342765     banana       1

In [13]:
index1 = {"name":data['label'].unique(),
         "number":data['label1'].unique()}  

In [14]:
df = pd.DataFrame(index1,columns = ['name','number'])
df.head(12)

name  number
0      grapes       7
1   mothbeans      13
2      lentil      10
3       mango      12
4       apple       0
5      cotton       6
6      coffee       5
7    chickpea       3
8   blackgram       2
9      banana       1
10    coconut       4
11      maize      11

In [15]:
df.sort_values(by = ['number'],ascending = True,inplace = True)
df

name  number
4         apple       0
9        banana       1
8     blackgram       2
7      chickpea       3
10      coconut       4
6        coffee       5
5        cotton       6
0        grapes       7
19         jute       8
21  kidneybeans       9
2        lentil      10
11        maize      11
3         mango      12
1     mothbeans      13
17     mungbean      14
20    muskmelon      15
13       orange      16
12       papaya      17
16   pigeonpeas      18
14  pomegranate      19
18         rice      20
15   watermelon      21

In [16]:
index2 = df['name']
index2 = list(index2)
print(index2)

['apple', 'banana', 'blackgram', 'chickpea', 'coconut', 'coffee', 'cotton', 'grapes', 'jute', 'kidneybeans', 'lentil', 'maize', 'mango', 'mothbeans', 'mungbean', 'muskmelon', 'orange', 'papaya', 'pigeonpeas', 'pomegranate', 'rice', 'watermelon']


In [17]:
x = data.iloc[:,0:4].values
y = data.iloc[:,5:].values
y

array([[ 7],
       [13],
       [10],
       ...,
       [ 6],
       [ 4],
       [ 0]])

In [18]:
x.shape

(2200, 4)

In [19]:
x

array([[ 12.14190714,  83.56812483,   5.64720239,  69.63122027],
       [ 30.88883074,  52.62696801,   8.63492974,  55.51932414],
       [ 27.99627907,  68.6428593 ,   7.32710972,  46.10585191],
       ...,
       [ 22.04612876,  84.62978302,   6.14463179,  86.00758678],
       [ 26.93141945,  98.80313612,   5.67154928, 166.5712879 ],
       [ 23.80436344,  92.80441624,   6.02424879, 100.6192543 ]])

In [20]:
y

array([[ 7],
       [13],
       [10],
       ...,
       [ 6],
       [ 4],
       [ 0]])

In [21]:
y.shape

(2200, 1)

In [22]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x,y,test_size = 0.2,random_state =2)

In [23]:
# RABDOM FOREST 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree
acc=[]
model=[]
regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(Xtrain,Ytrain)

predicted_values = regressor.predict(Xtest)

x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('RF')
print("RF's Accuracy is: ", x)

print(classification_report(Ytest,predicted_values))

E:\Users\sai\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


RF's Accuracy is:  0.9522727272727273
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        21
           1       0.93      1.00      0.97        28
           2       0.96      1.00      0.98        22
           3       1.00      1.00      1.00        20
           4       1.00      1.00      1.00        17
           5       0.96      1.00      0.98        24
           6       1.00      0.78      0.88        23
           7       0.86      1.00      0.92        18
           8       0.94      0.94      0.94        16
           9       1.00      1.00      1.00        17
          10       0.96      1.00      0.98        22
          11       0.95      0.95      0.95        19
          12       0.90      1.00      0.95        19
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        17
          15       1.00      1.00      1.00        21
          16       0.90      0.90      0.90

In [24]:
# NAVIE_BAYES
from sklearn.naive_bayes import GaussianNB

NaiveBayes = GaussianNB()

NaiveBayes.fit(Xtrain,Ytrain)
acc1 =[]
model1 =[]
predicted_values1 = NaiveBayes.predict(Xtest)
x1= metrics.accuracy_score(Ytest, predicted_values1)
acc1.append(x1)
model1.append('Naive Bayes')
print("Naive Bayes's Accuracy is: ", x1)

print(classification_report(Ytest,predicted_values1))

Naive Bayes's Accuracy is:  0.9636363636363636
              precision    recall  f1-score   support

           0       0.91      0.95      0.93        21
           1       0.97      1.00      0.98        28
           2       1.00      1.00      1.00        22
           3       1.00      1.00      1.00        20
           4       1.00      1.00      1.00        17
           5       1.00      1.00      1.00        24
           6       1.00      0.87      0.93        23
           7       0.95      1.00      0.97        18
           8       1.00      0.94      0.97        16
           9       1.00      1.00      1.00        17
          10       0.96      1.00      0.98        22
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00        19
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        17
          15       1.00      1.00      1.00        21
          16       0.85      0.85 

E:\Users\sai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [25]:
#index = ['mungbean','pomegranate','pigeonpeas','chickpea','papaya','lentil','cotton', 'jute','grapes',
#'coffee','apple','maize', 'coconut',  'banana','mango','blackgram','orange', 'rice','watermelon',
#'mothbeans','kidneybeans']

In [26]:
#index = data['label']

In [27]:
y_p = regressor.predict(np.array([[27.35152643,55.99375012,7.13411409,148.98125249999998]]))
y_list = (y_p.flatten('F'))
import pandas as pd
pd.set_option('display.max_columns', 34)
print(data[:9])
y_list = int(y_list)
print("----------------------------------")
print(y_list)
print("the suitable crop is",index2[y_list])

      temperature   humidity        ph    rainfall      label  label1
1207    12.141907  83.568125  5.647202   69.631220     grapes       7
587     30.888831  52.626968  8.634930   55.519324  mothbeans      13
893     27.996279  68.642859  7.327110   46.105852     lentil      10
1127    29.980805  49.486133  6.442393   91.822716      mango      12
1508    21.911913  91.687481  6.499227  117.076128      apple       0
1905    24.694571  81.735888  6.628723   78.584944     cotton       6
1132    35.787774  51.941903  5.395276  100.216061      mango      12
2183    24.592457  56.468296  7.288212  137.704405     coffee       5
278     19.462104  18.728320  7.217018   68.814051   chickpea       3
----------------------------------
5
the suitable crop is coffee


In [28]:
y_p1 = NaiveBayes.predict(np.array([[27.35152643,55.99375012,7.13411409,148.98125249999998]]))
y_list1 = (y_p1.flatten('F'))
import pandas as pd
pd.set_option('display.max_columns', 34)
print(data[:9])
y_list1 = int(y_list1)
print("----------------------------------")
print(y_list1)
print("the suitable crop is",index2[y_list1])

      temperature   humidity        ph    rainfall      label  label1
1207    12.141907  83.568125  5.647202   69.631220     grapes       7
587     30.888831  52.626968  8.634930   55.519324  mothbeans      13
893     27.996279  68.642859  7.327110   46.105852     lentil      10
1127    29.980805  49.486133  6.442393   91.822716      mango      12
1508    21.911913  91.687481  6.499227  117.076128      apple       0
1905    24.694571  81.735888  6.628723   78.584944     cotton       6
1132    35.787774  51.941903  5.395276  100.216061      mango      12
2183    24.592457  56.468296  7.288212  137.704405     coffee       5
278     19.462104  18.728320  7.217018   68.814051   chickpea       3
----------------------------------
5
the suitable crop is coffee


In [29]:
#import pickle
# Save the Modle to file in the current working directory

#Pkl_Filename = "Crop_Recom_Model.pkl"  

#with open(Pkl_Filename, 'wb') as file:  
#   pickle.dump(regressor, file)

In [30]:
#with open(Pkl_Filename, 'rb') as file:  
#    Pickled_Model = pickle.load(file)

#Pickled_Model

RandomForestClassifier(n_estimators=20, random_state=0)

In [31]:
#p = Pickled_Model.predict(np.array([[27.35152643,55.99375012,7.13411409,148.98125249999998]]))
#ylist = int(p.flatten('F'))
#print("the suitable crop is",index2[y_list])

the suitable crop is coffee


In [ ]:
#import pandas as pd
#pd.set_option('display.max_columns', 34)
#print(data[:9])
#ylist = int(ylist)
#print("----------------------------------")
#print(ylist)